create table if not exists public.research_papers (
  id bigint generated by default as identity primary key,
  category_id text not null,
  category_name text not null,
  category_sort int not null default 100,
  paper_sort int not null default 100,
  title text not null,
  organization text not null,
  summary text not null,
  url text not null,
  section1_heading text not null,
  section1_body text not null,
  section2_heading text not null,
  section2_body text not null,
  section3_heading text not null,
  section3_body text not null,
  section4_heading text not null,
  section4_body text not null,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.research_papers enable row level security;

grant usage on schema public to anon;
grant select on table public.research_papers to anon;

drop policy if exists "public read research_papers" on public.research_papers;

create policy "public read research_papers"
on public.research_papers
for select
to anon
using (published = true);

create index if not exists idx_research_papers_category_sort
on public.research_papers (category_sort, paper_sort, id);

create table if not exists public.farm_updates (
  id bigint generated by default as identity primary key,
  sort_order int not null default 100,
  date_label text not null,
  title text not null,
  description text not null,
  photo1_src text,
  photo1_alt text,
  photo1_caption text,
  photo2_src text,
  photo2_alt text,
  photo2_caption text,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.farm_updates enable row level security;

grant select on table public.farm_updates to anon;

drop policy if exists "public read farm_updates" on public.farm_updates;

create policy "public read farm_updates"
on public.farm_updates
for select
to anon
using (published = true);

create index if not exists idx_farm_updates_sort
on public.farm_updates (sort_order, id);

-- ================================================================
-- 管理者画面用 書き込み権限（開発モード：anon に全操作を許可）
-- TODO: 本番公開前に以下のポリシーを削除し、
--       authenticated ロール + Supabase Auth を使った
--       INSERT/UPDATE/DELETE ポリシーに置き換えること。
-- ================================================================

-- anon に INSERT/UPDATE/DELETE 権限を付与
grant insert, update, delete on table public.research_papers to anon;
grant insert, update, delete on table public.farm_updates to anon;

-- research_papers 書き込みポリシー（開発用）
drop policy if exists "dev anon write research_papers" on public.research_papers;
create policy "dev anon write research_papers"
on public.research_papers
for all
to anon
using (true)
with check (true);

-- farm_updates 書き込みポリシー（開発用）
drop policy if exists "dev anon write farm_updates" on public.farm_updates;
create policy "dev anon write farm_updates"
on public.farm_updates
for all
to anon
using (true)
with check (true);

-- ----------------------------------------------------------------
-- enjoy_entries テーブル（楽しみ方ページ用）
-- ----------------------------------------------------------------
create table if not exists public.enjoy_entries (
  id          bigint generated by default as identity primary key,
  sort_order  int not null default 10,
  title       text not null,
  description text not null,
  image_src   text,
  image_alt   text,
  published   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

alter table public.enjoy_entries enable row level security;

grant usage on schema public to anon;
grant select, insert, update, delete on table public.enjoy_entries to anon;

drop policy if exists "public read enjoy_entries" on public.enjoy_entries;
create policy "public read enjoy_entries"
on public.enjoy_entries for select to anon
using (published = true);

drop policy if exists "dev anon write enjoy_entries" on public.enjoy_entries;
create policy "dev anon write enjoy_entries"
on public.enjoy_entries for all to anon
using (true) with check (true);

create index if not exists idx_enjoy_entries_sort
on public.enjoy_entries (sort_order, id);

-- ----------------------------------------------------------------
-- product_entries テーブル（商品ページ用）
-- ----------------------------------------------------------------
create table if not exists public.product_entries (
  id          bigint generated by default as identity primary key,
  sort_order  int not null default 10,
  category    text,
  name        text not null,
  description text,
  price       int,
  image_src   text,
  image_alt   text,
  published   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

alter table public.product_entries enable row level security;

grant select, insert, update, delete on table public.product_entries to anon;

drop policy if exists "public read product_entries" on public.product_entries;
create policy "public read product_entries"
on public.product_entries for select to anon
using (published = true);

drop policy if exists "dev anon write product_entries" on public.product_entries;
create policy "dev anon write product_entries"
on public.product_entries for all to anon
using (true) with check (true);

create index if not exists idx_product_entries_sort
on public.product_entries (sort_order, id);

-- ----------------------------------------------------------------
-- 管理者ロール管理（Supabase Auth 連携）
-- ----------------------------------------------------------------
-- このテーブルは auth.users と 1:1 で紐づく管理者権限情報です。
-- 初回管理者は Supabase SQL Editor で手動登録してください。
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'admin',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

grant usage on schema public to authenticated;
grant select, insert, update, delete on table public.admin_users to authenticated;

-- ログインユーザーが管理者かどうかを判定する補助関数
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users au
    where au.user_id = auth.uid()
      and au.is_active = true
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

-- 自分の管理者プロフィールは参照可能
drop policy if exists "admin users read own" on public.admin_users;
create policy "admin users read own"
on public.admin_users
for select
to authenticated
using (auth.uid() = user_id);

-- 管理者は admin_users を管理可能
drop policy if exists "admins manage admin users" on public.admin_users;
create policy "admins manage admin users"
on public.admin_users
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- 初回管理者登録例（Authでユーザー作成後に実行）:
-- insert into public.admin_users (user_id, role, is_active)
-- values ('<auth.users.id の UUID>', 'owner', true);

-- ----------------------------------------------------------------
-- 本番向け切替: authenticated + is_admin() のみ書き込み許可
-- ----------------------------------------------------------------
-- このブロックはファイル全体を実行した最後に適用され、
-- 先に作られた開発用 anon 書き込みポリシーを無効化します。

-- authenticated ロールにデータ管理テーブルの操作権限を付与
grant usage on schema public to authenticated;
grant select, insert, update, delete on table public.research_papers to authenticated;
grant select, insert, update, delete on table public.farm_updates to authenticated;
grant select, insert, update, delete on table public.enjoy_entries to authenticated;
grant select, insert, update, delete on table public.product_entries to authenticated;

-- anon の書き込み権限を撤回（公開閲覧は維持）
revoke insert, update, delete on table public.research_papers from anon;
revoke insert, update, delete on table public.farm_updates from anon;
revoke insert, update, delete on table public.enjoy_entries from anon;
revoke insert, update, delete on table public.product_entries from anon;

-- 開発用 anon 書き込みポリシーを削除
drop policy if exists "dev anon write research_papers" on public.research_papers;
drop policy if exists "dev anon write farm_updates" on public.farm_updates;
drop policy if exists "dev anon write enjoy_entries" on public.enjoy_entries;
drop policy if exists "dev anon write product_entries" on public.product_entries;

-- 管理者のみ全操作可能（下書き閲覧含む）
drop policy if exists "admins manage research_papers" on public.research_papers;
create policy "admins manage research_papers"
on public.research_papers
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admins manage farm_updates" on public.farm_updates;
create policy "admins manage farm_updates"
on public.farm_updates
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admins manage enjoy_entries" on public.enjoy_entries;
create policy "admins manage enjoy_entries"
on public.enjoy_entries
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admins manage product_entries" on public.product_entries;
create policy "admins manage product_entries"
on public.product_entries
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- ----------------------------------------------------------------
-- qa_items テーブル（Q&Aページ用）
-- ----------------------------------------------------------------
create table if not exists public.qa_items (
  id          bigint generated by default as identity primary key,
  sort_order  int not null default 100,
  tag         text not null,
  question    text not null,
  answer      text not null,
  published   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

alter table public.qa_items enable row level security;

grant select on table public.qa_items to anon;
grant select, insert, update, delete on table public.qa_items to authenticated;

drop policy if exists "public read qa_items" on public.qa_items;
create policy "public read qa_items"
on public.qa_items for select to anon
using (published = true);

drop policy if exists "dev anon write qa_items" on public.qa_items;
create policy "dev anon write qa_items"
on public.qa_items for all to anon
using (true) with check (true);

drop policy if exists "admins manage qa_items" on public.qa_items;
create policy "admins manage qa_items"
on public.qa_items for all to authenticated
using (true) with check (true);

grant insert, update, delete on table public.qa_items to anon;

create index if not exists idx_qa_items_sort
on public.qa_items (sort_order, id);

-- ----------------------------------------------------------------
-- qa_logs テーブル（Q&A検索ログ用）
-- ----------------------------------------------------------------
create table if not exists public.qa_logs (
  id          bigint generated by default as identity primary key,
  query_text  text not null,
  hit_count   int not null default 0,
  searched_at timestamptz not null default now(),
  confirmed   boolean not null default false
);

alter table public.qa_logs
add column if not exists confirmed boolean not null default false;

alter table public.qa_logs enable row level security;

grant insert on table public.qa_logs to anon;
grant select, insert, update, delete on table public.qa_logs to authenticated;

drop policy if exists "anon insert qa_logs" on public.qa_logs;
create policy "anon insert qa_logs"
on public.qa_logs for insert to anon
with check (true);

drop policy if exists "admins manage qa_logs" on public.qa_logs;
create policy "admins manage qa_logs"
on public.qa_logs
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create index if not exists idx_qa_logs_query
on public.qa_logs (query_text, searched_at desc);
